from typing import Protocol


class AppCoordinatorProtocol(Protocol):
    def start_app(self) -> None: ...

    def open_main_menu_window(self) -> None: ...

    def open_reports_window(self) -> None: ...

    def open_protocols_window(self) -> None: ...


class ReportsCoordinatorProtocol(Protocol):
    def start_report_session(self) -> None: ...

    def open_main_menu_window(self) -> None: ...

    def open_division_window(self) -> None: ...

    def open_employee_window(self) -> None: ...

    def open_work_type_window(self) -> None: ...

    def open_work_window(self) -> None: ...

    def open_order_window(self) -> None: ...

    def open_work_event_window(self) -> None: ...


class ProtocolsCoordinatorProtocol(Protocol):
    def start_protocol_session(self) -> None: ...

    def open_main_menu_window(self) -> None: ...
