from __future__ import annotations

from typing import TYPE_CHECKING, Protocol

from src.core.models.company_domain import CompanyDomain
from src.core.models.department_domain import DepartmentDomain

if TYPE_CHECKING:
    from src.core.models.division_domain import DivisionDomain


class CompanyRepositoryProtocol(Protocol):
    @property
    def all_companies(self) -> list[CompanyDomain]: ...

    def get_company_by_id(self, company_id: int) -> CompanyDomain: ...

    @property
    def all_divisions(self) -> list[DivisionDomain]: ...

    def is_division_name_exists(self, name: str) -> bool: ...

    def is_department_name_exists(self, name: str) -> bool: ...

    def add_new_division(self, division: DivisionDomain) -> DivisionDomain: ...

    def add_new_department(self, department: DepartmentDomain) -> DepartmentDomain: ...

    def edit_division_by_id(self, division_id: int, division: DivisionDomain) -> DivisionDomain: ...

    def edit_department_by_id(
        self, department_id: int, department: DepartmentDomain
    ) -> DepartmentDomain: ...

    def delete_division_by_id(self, division_id: int) -> None: ...

    def delete_department_by_id(self, department_id: int) -> None: ...


class DivisionRepositoryProtocol(Protocol):
    @property
    def all_divisions(self) -> list[DivisionDomain]: ...

    def get_division_by_id(self, division_id: int) -> DivisionDomain: ...

    def divisions_of_company(self, company_id: int) -> list[DivisionDomain]: ...

    def is_division_name_exists(self, name: str) -> bool: ...

    def add_new_division(self, division: DivisionDomain) -> DivisionDomain: ...

    def edit_division_by_id(self, division_id: int, division: DivisionDomain) -> DivisionDomain: ...

    def delete_division_by_id(self, division_id: int) -> None: ...


class DepartmentRepositoryProtocol(Protocol):
    @property
    def all_departments(self) -> list[DepartmentDomain]: ...

    def get_department_by_id(self, department_id: int) -> DepartmentDomain: ...

    def departments_of_division(self, division_id: int) -> list[DepartmentDomain]: ...

    def is_department_name_exists(self, name: str) -> bool: ...

    def add_new_department(self, department: DepartmentDomain) -> DepartmentDomain: ...

    def edit_department_by_id(
        self, department_id: int, department: DepartmentDomain
    ) -> DepartmentDomain: ...

    def delete_department_by_id(self, department_id: int) -> None: ...